services:
  - type: web
    name: reddit-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python reddit_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7635656272AAHVnxiljBFJevrBXUAIQ-FD687BfPHiJbc
      - key: CHAT_ID
        value: 1601980040
